#include <vector>
#include "model.hpp"
#define SIMU 1
#define VERI 0
using namespace std;int main(){
    Model cpp_Model;
    cpp_Model.setDimensions(6);
    cpp_Model.setNumModes(2);
    cpp_Model.setInitialModeIdx(1);
    cpp_Model.setNumInitialEqns(12);
    cpp_Model.setNumUnsafeEqns(3);
    cpp_Model.setAnnotType(3);
    cpp_Model.setRefineStrat(0);
    cpp_Model.setSimulationBool(0);
    vector<int> mode_linear_dv;
    mode_linear_dv.push_back(1);
    mode_linear_dv.push_back(1);
    cpp_Model.setModeLinear(mode_linear_dv);
    cpp_Model.setAbsError(1e-10);
    cpp_Model.setRelError(1e-09);
    cpp_Model.setTimeStep(0.1);
    cpp_Model.setTimeHorizon(300.0);
    vector<double> gammas_dv;
    gammas_dv.push_back(-0.020000260873814596);
    gammas_dv.push_back(-0.030000031228404594);
    cpp_Model.setGammas(gammas_dv);
    vector<double> k_consts_dv;
    k_consts_dv.push_back(4.341086820425038);
    k_consts_dv.push_back(27.24422545275809);
    cpp_Model.setKConsts(k_consts_dv);
    vector<double> initial_matrix_dv;
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(10.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-10.0);
    initial_matrix_dv.push_back(10.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-10.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(10.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-10.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(-1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(1.0);
    initial_matrix_dv.push_back(0.0);
    initial_matrix_dv.push_back(0.0);
    cpp_Model.setInitialMatrix(initial_matrix_dv);
    vector<double> initial_b_dv;
    initial_b_dv.push_back(0.0);
    initial_b_dv.push_back(0.0);
    initial_b_dv.push_back(10.0);
    initial_b_dv.push_back(-10.0);
    initial_b_dv.push_back(-8750.0);
    initial_b_dv.push_back(9250.0);
    initial_b_dv.push_back(-3750.0);
    initial_b_dv.push_back(4250.0);
    initial_b_dv.push_back(0.0);
    initial_b_dv.push_back(0.0);
    initial_b_dv.push_back(0.0);
    initial_b_dv.push_back(0.0);
    cpp_Model.setInitialB(initial_b_dv);
    vector<double> unsafe_matrix_dv;
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(10.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(-10.0);
    unsafe_matrix_dv.push_back(10.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    unsafe_matrix_dv.push_back(0.0);
    cpp_Model.setUnsafeMatrix(unsafe_matrix_dv);
    vector<double> unsafe_b_dv;
    unsafe_b_dv.push_back(20.0);
    unsafe_b_dv.push_back(-20.0);
    unsafe_b_dv.push_back(-1000.0);
    cpp_Model.setUnsafeB(unsafe_b_dv);
    cpp_Model.setVisualizeFilename("../work-dir/LOS1");
    cpp_Model.setExecutable("../work-dir/simulator");
    cpp_Model.simulateVerify();
}

